### ISSUE TITLE
Bow marked as MMOItems

### ISSUE THREAD

**Issue by newbie029** [Indyuce/mmoitems#31]
**Describe the bug**
I made a MMOItems addon for my server to prevent MMOItems to attack player.
There are a problem with Bow, It always marked as a MMOItems even when it wasnt.

I use `MMOItems.plugin.getNMS().getNBTItem(item).getType() != null` to check if it was a MMOItems or not.

**Server info:**
 - Paperspigot 1.12.2 latest build
 - MMOItems Premium v4.7.9

**Comment by Indyuce** [comment]
Tell me how to replicate the issue.

**Comment by newbie029** [comment]
Ah sorry, Non-mmoitems bow marked as customprojectile
I use `MMOItems.plugin.getEntities().isCustomProjectile(pro)` to check it

**Comment by Indyuce** [comment]
Since some 4.7.x update, any arrow shot by any bow/player is considered a "custom projectile" because the projectiles saves some data about the player like its stats (crit strike, PvP/PvE damage...) and the item he used to show the arrow.
If that data was not stored, any non-MMOItems bows would not apply on-hit effects like on-hit abilities, crits and other weapon stats. Registering projectile data even when not firing an arrow from a MMOItems bow is therefore mandatory.

There is however a workaround. Just get the projectile data using `MMOItems.plugin.getEntities().getProjectileData(arrow)` and use the `ProjectileData#isCustomWeapon()` method which returns `true` if the weapon used is a bow from MMOItems.

**Comment by newbie029** [comment]
Working correctly, Thanks
