### ISSUE TITLE
Crafting Stations permission, Silver Ingot and Skill/Abilities not working

### ISSUE THREAD

**Issue by EtherGamer** [Indyuce/mmoitems#45]
I'm having trouble using abilities that every ability I used doesn't work and I noticed there were errors such as these.
https://pastebin.com/z0XU8gQs

and can what's the permission for the crafting stations since I want the players to manually input it.

And lastly Silver Ingot is not showing the Recipe :(

**Comment by Indyuce** [comment]
**Abilities Issue**
Double check your console for extra startup/join error logs. I've checked MI code and cannot see any obvious reason why this issue would occur on its own..

**Silver Ingot Issue**
Dupe of https://github.com/Indyuce/mmoitems/issues/45, the silver ingot was due to an outdated advanced workbench recipe in the default material.yml config. Will be fixed in the next update, however you will have to update it on your end as well: scroll all the way down to the advanced recipe of the silver ingot, and replace all `MISCELLANEOUS` references to `MATERIAL` (silver coin is a material and not a misc item).

**Recipe Command Permission**
There is no permission for the stations MI command because it's an admin command (not supposed to be used by players). However you could create a plugin command using an extra player and make it perform that admin command through the console. You can also bind this command to a block or an NPC (I would NPCs are an easier and better solution).

**Comment by EtherGamer** [comment]
I'm using 1.14.4 Spigot and if necessary the plugin called "ManaAndStamina" is just on my plugin folder not on the "addon" just in case. Is it recommended to have other plugins such as "MMOCore" to make the abilities work due to mana (even though the abilities I've put doesn't need mana)

**Comment by EtherGamer** [comment]
Nvm, It just needed the update for the abilities to work :) Thank you for your time!
