### ISSUE TITLE
Crafting Improvement

### ISSUE THREAD

**Issue by DogeTennant** [Indyuce/mmoitems#78]
When creating a crafting recipe, I'd like to be able to add multiple pieces of one item to the same slot in the craftin table.. (Imagine for example iron leggings, you need 7 iron ingots to create one pair of leggings, but now, yo would need 7 iron ingots for each slot of these 7 slots to create this one pair), on your wiki it is described as possible with the "amount=xx" but that simply doesn't work.

**Comment by Indyuce** [comment]
Would require a major workaround with the MC workbench. I don't think Mojang will be adding this type of crafting feature anytime soon.
We had this option a while ago when the advanced workbench was still a thing but we had to remove it due to all the glitches we had to take care of. The best solution atm is to use crafting stations which do support item amounts.
